AWSTemplateFormatVersion: "2010-09-09"
Description: A/B testing deployment 

Parameters:
  Universe:
    Description: Universe
    Type: String
    Default: dev
    AllowedValues:
      - dev

Mappings:
  TaskParams:
    dev:
      CPU: 1028
      RAM: 1096
      Heap: 999

Resources:
  EcsCluster:
    Type: AWS::ECS::Cluster

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      # (Your existing configuration for TaskRole)

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsCluster  # Reference the EcsCluster resource
      LaunchType: FARGATE
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 30
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          # (Your existing configuration for AwsvpcConfiguration)

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub A_B_Testing-${Universe}
      TaskRoleArn: !GetAtt TaskRole.Arn
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: !FindInMap [ TaskParams, !Ref Universe, CPU ]
      Memory: !FindInMap [ TaskParams, !Ref Universe, RAM ]
      ContainerDefinitions:
        - Name: A/B_TestingContainer
          Image: A/B_TestingImage
          Environment:
            - Name: ECS_FARGATE
              Value: "true"
            - Name: DD_RECEIVER_PORT
              Value: "8125"
            - Name: DD_HOSTNAME
              Value: !Sub ${Universe}-emodb-A/B_Testing-${AWS::Region}
            - Name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              Value: "true"
            - Name: DD_TAGS
              Value: !Sub service:A/B_Testing universe:${Universe} env:${Universe} bv:nexus:team:emodb-dev@bazaarvoice.com region:${AWS::Region}

  # LogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub /aws/ecs/emodb/megabus/${Universe}${DnsSuffix}
  #     RetentionInDays: 14