name: AWS CloudFormation Deployment

on:
    workflow_dispatch:
        inputs:
           Universe:
             description: 'Universe'
             required: true
             default: 'dev'

    
env:
    aws-region: ap-south-1
    

permissions:
    id-token: write
    contents: read
    actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::058264087706:role/TestingAB
        role-session-name: emojiSession
        aws-region: ${{env.aws-region}}

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy --stack-name abtestdeployment --template-file normecs.yml --capabilities CAPABILITY_NAMED_IAM --parameters 'ParameterKey=SubnetID,ParameterValue=subnet-0961246da2943af47'
      

  # Add more jobs or steps as needed
